import { Router, Request, Response, NextFunction } from "express";
import path from "path";
import { createContextLogger } from "../../utils/logger";
import { readFileSafe, writeFileEnsuringDir } from "../../utils/file-io";
import {
  extractTitle,
  extractMeta,
  extractSections,
  countUserStories,
  countApiEndpoints,
  validateSections,
} from "../../utils/markdown";
import { SPEC_REQUIRED_SECTIONS } from "../../schemas/spec.schema";
import { createStage, PipelineContext } from "../../runner/pipeline";
import { OneshotBuilderOutput } from "../../agents/types";

const log = createContextLogger("api-build");
const router = Router();

/**
 * POST /api/build/oneshot
 * Run a one-shot build from a spec file.
 * Streams SSE progress events for each pipeline stage.
 */
router.post("/oneshot", async (req: Request, res: Response, next: NextFunction) => {
  try {
    const { specPath, outputDir } = req.body;

    if (!specPath || typeof specPath !== "string") {
      res.status(400).json({ success: false, error: "Missing required field: specPath" });
      return;
    }

    log.info("API: Starting one-shot build", { specPath });

    // Set up SSE streaming response
    res.writeHead(200, {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-cache",
      Connection: "keep-alive",
      "Access-Control-Allow-Origin": "*",
    });

    const sendEvent = (event: string, data: unknown) => {
      res.write(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`);
    };

    const resolvedSpecPath = path.resolve(specPath);
    const resolvedOutputDir = outputDir ? path.resolve(outputDir) : path.resolve("./build-output");

    // Define pipeline stages
    const validateSpec = createStage<string, { valid: boolean; content: string }>(
      "validate-spec", "Validate spec.md against required sections",
      async (inputSpecPath) => {
        const content = readFileSafe(inputSpecPath);
        if (!content) throw new Error(`Spec file not found: ${inputSpecPath}`);
        const validation = validateSections(content, [...SPEC_REQUIRED_SECTIONS]);
        if (!validation.valid) throw new Error(`Spec missing sections: ${validation.missing.join(", ")}`);
        return { valid: true, content };
      }
    );

    const parseSpec = createStage<{ valid: boolean; content: string }, { parsed: Record<string, unknown>; content: string }>(
      "parse-spec", "Parse spec.md into structured data",
      async (input) => {
        const { content } = input;
        return {
          parsed: {
            title: extractTitle(content), version: extractMeta(content, "Version"),
            status: extractMeta(content, "Status"), sections: extractSections(content),
            userStoryCount: countUserStories(content), apiEndpointCount: countApiEndpoints(content),
          },
          content,
        };
      }
    );

    const generateScaffold = createStage<{ parsed: Record<string, unknown>; content: string }, { files: string[] }>(
      "generate-scaffold", "Generate project directory structure",
      async (input, ctx) => {
        const files: string[] = [];
        const parsed = input.parsed as { title?: string };
        const scaffold: Record<string, string> = {
          "package.json": JSON.stringify({ name: (parsed.title || "app").toLowerCase().replace(/\s+/g, "-"), version: "0.1.0", private: true, scripts: { dev: "echo Dev", build: "echo Build", test: "echo Test" } }, null, 2),
          "README.md": `# ${parsed.title || "Generated App"}\n\n> Generated by ADLC One-Shot Builder\n`,
          ".gitignore": "node_modules/\ndist/\n.env\n",
          "src/index.ts": `// Entry point for ${parsed.title || "app"}\nconsole.log("App initialized");\n`,
        };
        for (const [fileName, fileContent] of Object.entries(scaffold)) {
          const filePath = path.join(ctx.outputDir, fileName);
          if (!ctx.dryRun) writeFileEnsuringDir(filePath, fileContent);
          files.push(filePath);
        }
        return { files };
      }
    );

    const generateCode = createStage<{ files: string[] }, OneshotBuilderOutput>(
      "generate-code", "Generate application code from spec",
      async (input, ctx) => {
        const specContent = readFileSafe(ctx.specPath) || "";
        const userStoryCount = countUserStories(specContent);
        const apiEndpointCount = countApiEndpoints(specContent);
        const generatedFiles = [...input.files];
        if (apiEndpointCount > 0) {
          const p = path.join(ctx.outputDir, "src", "routes", "index.ts");
          if (!ctx.dryRun) writeFileEnsuringDir(p, `// Auto-generated API routes\nimport { Router } from "express";\nconst router = Router();\nexport default router;\n`);
          generatedFiles.push(p);
        }
        if (userStoryCount > 0) {
          const p = path.join(ctx.outputDir, "src", "components", "index.ts");
          if (!ctx.dryRun) writeFileEnsuringDir(p, `// Auto-generated components\nexport {};\n`);
          generatedFiles.push(p);
        }
        return { filesGenerated: generatedFiles, iterations: 1, testsPassing: false, duration: 0 };
      }
    );

    // Execute pipeline with progress events
    const stages: Array<{ name: string; description: string; optional?: boolean; execute: (input: any, ctx: PipelineContext) => Promise<any> }> = [validateSpec, parseSpec, generateScaffold, generateCode];
    const totalStages = stages.length;

    sendEvent("progress", { step: 0, totalSteps: totalStages, stage: "initializing", label: "Initializing build pipeline...", percent: 0 });

    const context: PipelineContext = {
      workingDir: resolvedOutputDir, specPath: resolvedSpecPath,
      outputDir: resolvedOutputDir, config: {}, results: new Map(), dryRun: false,
    };

    const pipelineStart = Date.now();
    const stageResults: Array<{ stage: string; success: boolean; duration: number; error?: string }> = [];
    let currentInput: unknown = resolvedSpecPath;
    let pipelineSuccess = true;
    let failedStage: string | undefined;
    const errors: string[] = [];

    for (let i = 0; i < stages.length; i++) {
      const stage = stages[i];
      const stageNum = i + 1;
      const percent = Math.round((stageNum / totalStages) * 100);

      sendEvent("progress", { step: stageNum, totalSteps: totalStages, stage: stage.name, label: stage.description, percent });

      const stageStart = Date.now();
      try {
        const output = await stage.execute(currentInput, context);
        const duration = Date.now() - stageStart;
        stageResults.push({ stage: stage.name, success: true, duration });
        context.results.set(stage.name, output);
        currentInput = output;
        sendEvent("stage-complete", { stage: stage.name, success: true, duration, step: stageNum, totalSteps: totalStages });
      } catch (error) {
        const duration = Date.now() - stageStart;
        const message = error instanceof Error ? error.message : String(error);
        stageResults.push({ stage: stage.name, success: false, duration, error: message });
        pipelineSuccess = false;
        failedStage = stage.name;
        errors.push(`[${stage.name}] ${message}`);
        sendEvent("stage-complete", { stage: stage.name, success: false, duration, error: message, step: stageNum, totalSteps: totalStages });
        if (!stage.optional) break;
      }
    }

    const totalDuration = Date.now() - pipelineStart;
    const output = (context.results.get("generate-code") as OneshotBuilderOutput) || null;

    sendEvent("result", { success: pipelineSuccess, data: output, pipeline: { stages: stageResults, totalDuration, failedStage, errors } });
    sendEvent("done", {});
    res.end();
  } catch (error) {
    if (res.headersSent) {
      const message = error instanceof Error ? error.message : String(error);
      res.write(`event: error\ndata: ${JSON.stringify({ error: message })}\n\n`);
      res.write(`event: done\ndata: {}\n\n`);
      res.end();
    } else {
      next(error);
    }
  }
});

export default router;
