import path from "path";
import {
  Agent,
  AgentContext,
  AgentResult,
  SpecGeneratorInput,
  SpecGeneratorOutput,
} from "./types";
import { config } from "../config";
import { readFileSafe, writeFileEnsuringDir } from "../utils/file-io";
import { createContextLogger } from "../utils/logger";

const log = createContextLogger("spec-generator");

/**
 * Spec Generator Agent
 *
 * Given a high-level product idea or prompt, generates a comprehensive
 * spec.md containing business facts, API schemas, design system constraints,
 * and acceptance criteria.
 */
export class SpecGeneratorAgent
  implements Agent<SpecGeneratorInput, SpecGeneratorOutput>
{
  readonly name = "spec-generator";
  readonly description =
    "Generates comprehensive spec.md files from high-level product prompts";

  async execute(
    input: SpecGeneratorInput,
    context: AgentContext
  ): Promise<AgentResult<SpecGeneratorOutput>> {
    const startTime = Date.now();
    log.info("Starting spec generation", { prompt: input.prompt.substring(0, 100) });

    try {
      // 1. Load the spec template
      const template = readFileSafe(config.paths.specTemplate);
      if (!template) {
        return this.fail("Spec template not found at templates/spec.template.md", startTime);
      }

      // 2. Derive project name
      const projectName = input.projectName || this.deriveProjectName(input.prompt);
      log.info("Generating spec for project", { projectName });

      // 3. Generate spec content from prompt
      const specContent = this.generateSpecFromPrompt(
        template,
        projectName,
        input.prompt,
        input.constraints
      );

      // 4. Determine output path
      const outputPath = input.outputPath
        ? path.resolve(input.outputPath)
        : path.join(config.paths.specs, projectName, "spec.md");

      // 5. Write the spec file
      if (!context.dryRun) {
        const written = writeFileEnsuringDir(outputPath, specContent);
        if (!written) {
          return this.fail(`Failed to write spec to ${outputPath}`, startTime);
        }
        log.info("Spec written successfully", { outputPath });
      }

      // 6. Extract metadata
      const metadata = this.extractMetadata(specContent, projectName);

      return {
        success: true,
        data: {
          specContent,
          outputPath,
          metadata,
        },
        errors: [],
        warnings: context.dryRun ? ["Dry run — spec was not written to disk"] : [],
        duration: Date.now() - startTime,
        metadata: { projectName, dryRun: context.dryRun || false },
      };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      log.error("Spec generation failed", { error: message });
      return this.fail(message, startTime);
    }
  }

  /**
   * Generate spec content by populating the template with AI-derived content.
   * In production, this would call an LLM. Here we provide a structured scaffold
   * that agents/AI can fill in.
   */
  private generateSpecFromPrompt(
    template: string,
    projectName: string,
    prompt: string,
    constraints?: string[]
  ): string {
    const now = new Date().toISOString().split("T")[0];
    const constraintsBlock = constraints?.length
      ? `\n### Constraints\n${constraints.map((c) => `- ${c}`).join("\n")}\n`
      : "";

    // Replace template placeholders with actual values
    let spec = template
      .replace(/\{PROJECT_NAME\}/g, projectName)
      .replace(/\{VERSION\}/g, "0.1.0")
      .replace(/\{STATUS: draft \| review \| approved \| deprecated\}/g, "draft")
      .replace(/\{DATE\}/g, now)
      .replace(/\{OWNER\}/g, "V3 ADLC Engine");

    // Inject the prompt into the executive summary
    spec = spec.replace(
      /\{One-paragraph description of the product.*?\}/,
      `${prompt}${constraintsBlock}`
    );

    // Add generation metadata
    spec += `\n\n---\n\n> _Auto-generated by V3 ADLC Spec Generator Agent on ${now}_\n> _Source prompt: "${prompt.substring(0, 200)}"_\n`;

    return spec;
  }

  /**
   * Derive a project name from the prompt.
   */
  private deriveProjectName(prompt: string): string {
    // Extract key words and create a kebab-case name
    const words = prompt
      .toLowerCase()
      .replace(/[^a-z0-9\s]/g, "")
      .split(/\s+/)
      .filter((w) => w.length > 2)
      .slice(0, 4);

    return words.length > 0 ? words.join("-") : "unnamed-project";
  }

  /**
   * Extract metadata from generated spec content.
   */
  private extractMetadata(
    specContent: string,
    projectName: string
  ): SpecGeneratorOutput["metadata"] {
    const userStories = (specContent.match(/\|\s*US-\d+/g) || []).length;
    const apiEndpoints = (
      specContent.match(
        /####\s+`(GET|POST|PUT|PATCH|DELETE|HEAD|OPTIONS)\s+/gi
      ) || []
    ).length;
    const sections = (specContent.match(/^##\s+/gm) || []).length;

    return {
      projectName,
      version: "0.1.0",
      userStoryCount: userStories,
      apiEndpointCount: apiEndpoints,
      sectionCount: sections,
    };
  }

  private fail(message: string, startTime: number): AgentResult<SpecGeneratorOutput> {
    return {
      success: false,
      data: null,
      errors: [message],
      warnings: [],
      duration: Date.now() - startTime,
      metadata: {},
    };
  }
}

export default SpecGeneratorAgent;

// ─── CLI Entry Point ──────────────────────────────────────────────

if (require.main === module) {
  const { Command } = require("commander");
  const program = new Command();
  program
    .name("spec:generate")
    .description("Generate a spec.md from a product prompt")
    .requiredOption("--prompt <text>", "High-level product description")
    .option("--project <name>", "Project name (auto-derived if omitted)")
    .option("--output <path>", "Output path for spec.md")
    .option("--constraints <items>", "Comma-separated constraints")
    .option("--dry-run", "Preview without writing to disk", false)
    .action(async (opts: any) => {
      const agent = new SpecGeneratorAgent();
      const context = { workingDir: process.cwd(), dryRun: opts.dryRun || false };
      const constraints = opts.constraints
        ? opts.constraints.split(",").map((c: string) => c.trim())
        : undefined;

      const result = await agent.execute(
        {
          prompt: opts.prompt,
          projectName: opts.project,
          outputPath: opts.output,
          constraints,
        },
        context
      );

      if (result.success && result.data) {
        console.log("\n✅ Spec Generated Successfully");
        console.log(`   Project: ${result.data.metadata.projectName}`);
        console.log(`   Version: ${result.data.metadata.version}`);
        console.log(`   Sections: ${result.data.metadata.sectionCount}`);
        console.log(`   User Stories: ${result.data.metadata.userStoryCount}`);
        console.log(`   API Endpoints: ${result.data.metadata.apiEndpointCount}`);
        console.log(`   Output: ${result.data.outputPath}`);
        console.log(`   Duration: ${result.duration}ms`);
      } else {
        console.error("\n❌ Spec Generation Failed");
        console.error(`   Errors: ${result.errors.join(", ")}`);
        process.exit(1);
      }
    });

  program.parse();
}
