import path from "path";
import { Command } from "commander";
import { createContextLogger } from "../utils/logger";
import { readFileSafe, writeFileEnsuringDir } from "../utils/file-io";
import {
  extractTitle,
  extractMeta,
  extractSections,
  countUserStories,
  countApiEndpoints,
  validateSections,
} from "../utils/markdown";
import { SPEC_REQUIRED_SECTIONS } from "../schemas/spec.schema";
import {
  executePipeline,
  createStage,
  PipelineContext,
  PipelineResult,
} from "./pipeline";
import {
  OneshotBuilderInput,
  OneshotBuilderOutput,
} from "../agents/types";

const log = createContextLogger("oneshot-builder");

// ─── Pipeline Stages ─────────────────────────────────────────────

const validateSpec = createStage<string, { valid: boolean; content: string }>(
  "validate-spec",
  "Validate spec.md against required sections",
  async (specPath, _ctx) => {
    const content = readFileSafe(specPath);
    if (!content) throw new Error(`Spec file not found: ${specPath}`);

    const validation = validateSections(content, [...SPEC_REQUIRED_SECTIONS]);
    if (!validation.valid) {
      throw new Error(`Spec missing sections: ${validation.missing.join(", ")}`);
    }

    const title = extractTitle(content);
    const status = extractMeta(content, "Status");
    log.info("Spec validated", { title, status });

    return { valid: true, content };
  }
);

const parseSpec = createStage<
  { valid: boolean; content: string },
  { parsed: Record<string, unknown>; content: string }
>(
  "parse-spec",
  "Parse spec.md into structured data",
  async (input, _ctx) => {
    const { content } = input;
    const parsed = {
      title: extractTitle(content),
      version: extractMeta(content, "Version"),
      status: extractMeta(content, "Status"),
      sections: extractSections(content),
      userStoryCount: countUserStories(content),
      apiEndpointCount: countApiEndpoints(content),
    };
    log.info("Spec parsed", {
      userStories: parsed.userStoryCount,
      apiEndpoints: parsed.apiEndpointCount,
    });
    return { parsed, content };
  }
);

const generateScaffold = createStage<
  { parsed: Record<string, unknown>; content: string },
  { files: string[] }
>(
  "generate-scaffold",
  "Generate project directory structure",
  async (input, ctx) => {
    const files: string[] = [];
    const parsed = input.parsed as { title?: string };
    const projectDir = ctx.outputDir;

    const scaffoldFiles: Record<string, string> = {
      "package.json": JSON.stringify({
        name: (parsed.title || "generated-app").toLowerCase().replace(/\s+/g, "-"),
        version: "0.1.0",
        private: true,
        scripts: { dev: "echo 'Dev server'", build: "echo 'Build'", test: "echo 'Test'" },
      }, null, 2),
      "README.md": `# ${parsed.title || "Generated App"}\n\n> Generated by ADLC One-Shot Builder\n`,
      ".gitignore": "node_modules/\ndist/\n.env\n",
      "src/index.ts": `// Entry point for ${parsed.title || "app"}\nconsole.log("App initialized");\n`,
    };

    for (const [fileName, content] of Object.entries(scaffoldFiles)) {
      const filePath = path.join(projectDir, fileName);
      if (!ctx.dryRun) writeFileEnsuringDir(filePath, content);
      files.push(filePath);
    }

    log.info("Scaffold generated", { fileCount: files.length });
    return { files };
  }
);

const generateCode = createStage<{ files: string[] }, OneshotBuilderOutput>(
  "generate-code",
  "Generate application code from spec",
  async (input, ctx) => {
    const specContent = readFileSafe(ctx.specPath) || "";
    const userStoryCount = countUserStories(specContent);
    const apiEndpointCount = countApiEndpoints(specContent);
    const generatedFiles = [...input.files];

    if (apiEndpointCount > 0) {
      const routesPath = path.join(ctx.outputDir, "src", "routes", "index.ts");
      if (!ctx.dryRun) {
        writeFileEnsuringDir(routesPath,
          `// Auto-generated API routes\n// ${apiEndpointCount} endpoints from spec\n\nimport { Router } from "express";\nconst router = Router();\nexport default router;\n`
        );
      }
      generatedFiles.push(routesPath);
    }

    if (userStoryCount > 0) {
      const componentsPath = path.join(ctx.outputDir, "src", "components", "index.ts");
      if (!ctx.dryRun) {
        writeFileEnsuringDir(componentsPath,
          `// Auto-generated components\n// ${userStoryCount} user stories from spec\n\nexport {};\n`
        );
      }
      generatedFiles.push(componentsPath);
    }

    log.info("Code generation complete", { filesGenerated: generatedFiles.length });
    return {
      filesGenerated: generatedFiles,
      iterations: 1,
      testsPassing: false,
      duration: 0,
    };
  }
);

// ─── Main Builder ─────────────────────────────────────────────────

export async function runOneshotBuild(
  input: OneshotBuilderInput
): Promise<{ result: PipelineResult; output: OneshotBuilderOutput | null }> {
  const context: PipelineContext = {
    workingDir: input.outputDir,
    specPath: input.specPath,
    outputDir: input.outputDir,
    config: {},
    results: new Map(),
    dryRun: false,
  };

  const pipelineResult = await executePipeline(
    [validateSpec, parseSpec, generateScaffold, generateCode],
    input.specPath,
    context
  );

  const output = (context.results.get("generate-code") as OneshotBuilderOutput) || null;
  return { result: pipelineResult, output };
}

// ─── CLI Entry Point ──────────────────────────────────────────────

if (require.main === module) {
  const program = new Command();
  program
    .name("oneshot-builder")
    .description("One-Shot Spec-to-App Build Pipeline")
    .requiredOption("--spec <path>", "Path to spec.md file")
    .option("--output <dir>", "Output directory", "./build-output")
    .option("--mode <mode>", "Build mode: fresh or refactor", "fresh")
    .option("--dry-run", "Run without writing files", false)
    .action(async (opts) => {
      const specPath = path.resolve(opts.spec);
      const outputDir = path.resolve(opts.output);

      log.info("Starting One-Shot Build", { specPath, outputDir });

      const { result, output } = await runOneshotBuild({
        specPath,
        outputDir,
        mode: opts.mode,
      });

      if (result.success && output) {
        console.log("\n✅ One-Shot Build Complete");
        console.log(`   Files: ${output.filesGenerated.length}`);
        console.log(`   Duration: ${result.totalDuration}ms`);
      } else {
        console.error("\n❌ One-Shot Build Failed");
        console.error(`   Stage: ${result.failedStage}`);
        console.error(`   Error: ${result.errors.join(", ")}`);
        process.exit(1);
      }
    });

  program.parse();
}

